apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netmind.fullname" . }}-frontend
  labels:
    app: {{ include "netmind.name" . }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "netmind.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "netmind.name" . }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
