replicaCount: 1

backend:
  image:
    repository: netmind/backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8000
  env:
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    POSTGRES_DB: "netmind"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"

frontend:
  image:
    repository: netmind/frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
