"""add phase 5 fields

Revision ID: a4f2ac7265b3
Revises: 0971bfc6ff15
Create Date: 2026-10-01 14:45:32.495085

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f2ac7265b3'
down_revision: Union[str, None] = '0971bfc6ff15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_detections',
    sa.Column('anomaly_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('detector', sa.String(length=128), nullable=False),
    sa.Column('detector_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index(op.f('ix_anomaly_detections_device_id'), 'anomaly_detections', ['device_id'], unique=False)
    op.create_index(op.f('ix_anomaly_detections_timestamp'), 'anomaly_detections', ['timestamp'], unique=False)
    op.create_table('model_health',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inference_latency_avg', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('drift_metric', sa.String(length=128), nullable=True),
    sa.Column('ks_h0', sa.String(length=256), nullable=True),
    sa.Column('ks_statistic', sa.Float(), nullable=True),
    sa.Column('ks_p_value', sa.Float(), nullable=True),
    sa.Column('reference_window', sa.String(length=128), nullable=True),
    sa.Column('current_window', sa.String(length=128), nullable=True),
    sa.Column('drift_threshold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_health_model_name'), 'model_health', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_health_timestamp'), 'model_health', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=64), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('inference_latency', sa.Float(), nullable=True),
    sa.Column('input_window', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_predictions_device_id'), 'predictions', ['device_id'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('incident_audit',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_audit_incident_id'), 'incident_audit', ['incident_id'], unique=False)
    op.add_column('incidents', sa.Column('detection_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('triggering_metric', sa.String(length=128), nullable=True))
    op.add_column('incidents', sa.Column('observed_value', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('expected_value', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('related_telemetry', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('related_devices', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('topology_relationships', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('recent_config_changes', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('related_incidents', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('candidate_root_causes', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('recommended_actions', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('human_approval_state', sa.String(length=50), nullable=True))
    op.add_column('incidents', sa.Column('resolution', sa.String(), nullable=True))
    op.drop_column('incidents', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('incidents', 'resolution')
    op.drop_column('incidents', 'human_approval_state')
    op.drop_column('incidents', 'recommended_actions')
    op.drop_column('incidents', 'candidate_root_causes')
    op.drop_column('incidents', 'related_incidents')
    op.drop_column('incidents', 'recent_config_changes')
    op.drop_column('incidents', 'topology_relationships')
    op.drop_column('incidents', 'related_devices')
    op.drop_column('incidents', 'related_telemetry')
    op.drop_column('incidents', 'expected_value')
    op.drop_column('incidents', 'observed_value')
    op.drop_column('incidents', 'triggering_metric')
    op.drop_column('incidents', 'detection_timestamp')
    op.drop_index(op.f('ix_incident_audit_incident_id'), table_name='incident_audit')
    op.drop_table('incident_audit')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_device_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_health_timestamp'), table_name='model_health')
    op.drop_index(op.f('ix_model_health_model_name'), table_name='model_health')
    op.drop_table('model_health')
    op.drop_index(op.f('ix_anomaly_detections_timestamp'), table_name='anomaly_detections')
    op.drop_index(op.f('ix_anomaly_detections_device_id'), table_name='anomaly_detections')
    op.drop_table('anomaly_detections')
    # ### end Alembic commands ###
