"""Add Incident model

Revision ID: 8c6c8763bec5
Revises: 2a2454b62433
Create Date: 2026-09-30 16:26:00.894700

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c6c8763bec5"
down_revision: Union[str, None] = "2a2454b62433"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DETECTED",
                "INVESTIGATING",
                "CONFIRMED",
                "MITIGATED",
                "RESOLVED",
                "CLOSED",
                name="incidentstatus",
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incidents_correlation_id"), "incidents", ["correlation_id"], unique=True
    )
    op.create_index(op.f("ix_incidents_entity_id"), "incidents", ["entity_id"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_entity_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_correlation_id"), table_name="incidents")
    op.drop_table("incidents")
    # ### end Alembic commands ###
